### ISSUE TITLE
Software available?

### ISSUE THREAD

**Issue by privefl** [sgchun/nps#1]
Hello, 

I'm reading your paper "Non-parametric polygenic risk prediction using partitioned GWAS summary statistics".
I wonder if there is a public implementation of your method that I could try to use?

Thanks,
Florian Privé

**Comment by sgchun** [comment]
Dear Florian, 

Thank you for your interest, and I am very sorry for the delay in response. Yes, the software will be released in public by early Jan along with updated preprint in BioRxiv. 

Best, 

Sung
